[debug] not up to date. inChanged = true, force = false
[debug] Updating ...
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.storm-enroute:macrogl_2.13:0.4-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/ifkbhit/.ivy2/local/com.storm-enroute/macrogl_2.13/0.4-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/storm-enroute/macrogl_2.13/0.4-SNAPSHOT/macrogl_2.13-0.4-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/storm-enroute/macrogl_2.13/0.4-SNAPSHOT/macrogl_2.13-0.4-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/storm-enroute/macrogl_2.13/0.4-SNAPSHOT/macrogl_2.13-0.4-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at lmcoursier.CoursierDependencyResolution$$Lambda$4057.00000000E2AC4E20.apply(Unknown Source)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2864.00000000E3A81220.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.util.Tracked$$$Lambda$2772.00000000E68D1A20.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2866.00000000E4AEFA20.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2860.00000000E4107820.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.util.Tracked$$$Lambda$2624.00000000E562A620.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3440)
[error] 	at sbt.Classpaths$$$Lambda$617.00000000E4952C20.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at scala.Function1$$Lambda$291.00000000E7018020.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2450.00000000E4A24220.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2478.00000000E560C620.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$2461.00000000E4AC0020.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2475.00000000E3A70020.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:819)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.storm-enroute:macrogl_2.13:0.4-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/ifkbhit/.ivy2/local/com.storm-enroute/macrogl_2.13/0.4-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/storm-enroute/macrogl_2.13/0.4-SNAPSHOT/macrogl_2.13-0.4-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/storm-enroute/macrogl_2.13/0.4-SNAPSHOT/macrogl_2.13-0.4-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/storm-enroute/macrogl_2.13/0.4-SNAPSHOT/macrogl_2.13-0.4-SNAPSHOT.pom
